#!/bin/bash

drush site:install minimal --account-name=islandora --account-pass=islandora --existing-config -y

drush cache:rebuild
drush config:import -y

drush user:role:add fedoraadmin islandora

drush cache:rebuild
