---
volumes:
  activemq-data:
services:
  activemq:
    container_name: "ddev-${DDEV_SITENAME}-activemq"
    image: ${ISLANDORA_DOCKER_IMAGE_REPO}/activemq:${ISLANDORA_DOCKER_IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - activemq-data:/opt/activemq/data
    expose:
      - "8161"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - ddev-router:${DDEV_HOSTNAME}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8161:8161
    secrets:
      - ACTIVEMQ_PASSWORD
      - ACTIVEMQ_WEB_ADMIN_PASSWORD
    healthcheck:
      # XXX: The image has environment-specifics baked into the image, in
      # particular, dealing with
      # /var/run/s6/container_environment/ACTIVEMQ_WEB_ADMIN_PASSWORD
      # See: https://github.com/Islandora-Devops/isle-buildkit/blob/fe6e83ea6a3468d06ef4263b3efcfde8323e3f80/activemq/Dockerfile#L41C21-L41C82
      disable: true
