---
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: ${ISLANDORA_DOCKER_IMAGE_REPO}/solr:${ISLANDORA_DOCKER_IMAGE_TAG}
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - ddev-router:${DDEV_HOSTNAME}
    volumes:
      - "solr-data:/opt/solr/server/solr"
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983:8983
      # XXX: Add in list of modules, as things are not yet committed upstream.
      # See: https://github.com/Islandora-Devops/isle-buildkit/pull/431
      - SOLR_MODULES=extraction,langid,ltr,analysis-extras
volumes:
  solr-data:
