name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '42 4 * * *'
jobs:
  stale:
    uses: Islandora-Devops/.github/.github/workflows/stale.yaml@5a60996cabc8b9238ac564d88c246195978791d5 # main
    secrets: inherit
