name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '42 4 * * *'
jobs:
  stale:
    uses: Islandora-Devops/.github/.github/workflows/stale.yaml@c4d3f68f213a5579c2fbc58c6ee8dce187c37a23 # main
    secrets: inherit
