name: validate renovate.json5

on:
  pull_request:
    paths:
      - "renovate.json5"
env:
  LOG_LEVEL: debug

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - run: npx -p renovate renovate-config-validator renovate.json5
